### ISSUE TITLE
Zwischenergebnisse in DB anstatt in Memory speichern

### ISSUE THREAD

**Issue by johannesbrandenburger** [DHBW-FN-TIT20/sa-hs-lb-jb#13]
- [ ] Anlegen einer Datenbank (Docker o.ä.?)
- [ ] Erstellen eines DB-Handlers -> Export und Import funktionen

**Comment by schuler-henry** [comment]
@johannesbrandenburger Ich habe jetzt mal hier einen Exporter implementiert, der alles in eine Ordnerstruktur sichert.
Eigentlich enthält dieses Objekt ja alle verarbeiteten Daten.
Vorläufig können wir so also auch Daten austauschen.

Im Rahmen der Gesamtarchitektur müssen wir aber denke ich uns noch genauer anschauen wie wir mit unseren veränderbaren Größen umgehen wollen.

**Comment by johannesbrandenburger** [comment]
@schuler-henry Ja ich hätte eh gesagt, dass wir das Optimieren/Erweitern vom Code jetzt mal auf Eis legen bis wir nächste Woche das Konzept für die Architektur aufstellen...

**Comment by schuler-henry** [comment]
Wurde durch Lukas in anderer Form implementiert.
